#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

typedef struct book
{
    char *title;
    int release_date;
    float price;
}book;

typedef struct author
{
    int writer_id;
    char *surname;
    char *name;
    int num_of_books;
}author;

typedef struct writes
{
    char *title;
    int writer_id;
}writes;

int menu();
void bubble_sort_book(book *book_arr, int book_entries);
void swap_book(book *b1, book *b2);

void bubble_sort_author(author *author_arr, int author_entries);
void swap_author(author *author1, author *author2);

void bubble_sort_writes(writes *writes_arr, int writes_entries);
void swap_writes(writes *writes1, writes *writes2);

int author_search(author* author_arr, int author_entries, int in_id);
int writes_search_id(writes* writes_arr, int writes_entries, int in_writer_id);
int book_search(book* book_arr, int book_entries, char* in_title);

int main(int argc, char *argv[])
{
    int choice, book_entries, author_entries, writes_entries, i, in_id, book_pos=0, author_pos=0, writes_pos=0;
    struct book *book_arr;
    struct author *author_arr;
    struct writes *writes_arr;
    FILE *book_file, *author_file, *writes_file;
    char *in_surname, *in_title;

    in_surname = (char*) malloc(sizeof(char) * 150);
    in_title= (char*) malloc(sizeof(char) * 150);
    //read book file
    if ((book_file = fopen("book2.txt", "r")) == NULL ){
        fprintf(stderr, "File not found.\n");
        return -1;
    }	
    i=0;
    fscanf(book_file, "%d\n", &book_entries);
    book_arr = (book *)malloc(sizeof(book) * book_entries);
    while (!feof(book_file)){
        book_arr[i].title = (char*) malloc(sizeof(char) * 150);
        fscanf(book_file, "%[^\n]", book_arr[i].title);
        fscanf(book_file, "%d\n", &book_arr[i].release_date);
        fscanf(book_file, "%f\n", &book_arr[i].price);
        i++;
    }
    fclose(book_file);

    //read author file
	if ((author_file = fopen("author2.txt", "r")) == NULL ){
        fprintf(stderr, "File not found.\n");
        return -1;
    }
    i=0;
    fscanf(author_file, "%d\n", &author_entries);
    author_arr = (author *)malloc(sizeof(author) * author_entries);
    while (!feof(author_file)){
        fscanf(author_file, "%d\n", &author_arr[i].writer_id);
        author_arr[i].surname = (char*) malloc(sizeof(char) * 150);
        fscanf(author_file, "%s\n", author_arr[i].surname);
        author_arr[i].name = (char*) malloc(sizeof(char) * 150);
        fscanf(author_file, "%s\n", author_arr[i].name);
        fscanf(author_file, "%d\n", &author_arr[i].num_of_books);
        i++;
    }
    fclose(author_file);
    
    //read writes file
	if ((writes_file = fopen("writes2.txt", "r")) == NULL ){
        fprintf(stderr, "File not found.\n");
        return -1;
    }
    i=0;
    fscanf(writes_file, "%d\n", &writes_entries);
    writes_arr = (writes *)malloc(sizeof(writes) * writes_entries);
    while (!feof(writes_file)){
        writes_arr[i].title = (char*) malloc(sizeof(char) * 150);
        fscanf(writes_file, "%[^\n]", writes_arr[i].title);
        fscanf(writes_file, "%d\n", &writes_arr[i].writer_id);
        i++;
    }
    fclose(writes_file);

    //sort arrays
    bubble_sort_author(author_arr, author_entries);
	bubble_sort_book(book_arr,book_entries);
	bubble_sort_writes(writes_arr, writes_entries);

    choice = menu();
    
    while (choice != 7) {
        if (choice == 1) { //add author
            //increase number of author entries
            author_entries = author_entries + 1;
            //allocate space for new author
            author_arr = (author*) realloc(author_arr, sizeof(author) * (author_entries));
            author_arr[(author_entries-1)].surname = (char*) malloc(sizeof(char) * 150);
            author_arr[(author_entries-1)].name = (char*) malloc(sizeof(char) * 150);
			//get author info by user
            printf("Name: ");
            scanf("%s", author_arr[(author_entries-1)].name);
            printf("Surname: ");
			scanf("%s", author_arr[(author_entries-1)].surname);
            //user info generated by the program
            author_arr[(author_entries-1)].writer_id = author_arr[(author_entries-2)].writer_id + 1;
            author_arr[(author_entries-1)].num_of_books = 0;
            //sort author array
            bubble_sort_author(author_arr,author_entries);
            //save author array
	        if ((author_file = fopen("author2.txt", "w")) == NULL ){
                fprintf(stderr, "File not found.\n");
                return -1;
            }
            fprintf(author_file, "%d\n", author_entries);
            for (i=0;i<author_entries; i++){
                fprintf(author_file, "%d\n", author_arr[i].writer_id);
                fprintf(author_file, "%s\n", author_arr[i].surname);
                fprintf(author_file, "%s\n", author_arr[i].name);
                fprintf(author_file, "%d\n", author_arr[i].num_of_books);
            }
            fclose(author_file);
            choice = menu();		
        }
        else if (choice == 2) { //add book
            //increase number of book entries
            book_entries = book_entries + 1;
            //allocate space for new book
            book_arr = (book*) realloc(book_arr, sizeof(book) * (book_entries));
            book_arr[(book_entries-1)].title = (char*) malloc(sizeof(char) * 150);
			//get book info by user
            printf("Title: ");
            scanf(" %[^\n]", book_arr[(book_entries-1)].title);
            printf("Release date: ");
			scanf("%d", &book_arr[(book_entries-1)].release_date);
            printf("Price: ");
			scanf("%f", &book_arr[(book_entries-1)].price);
            //get author surname by user
            printf("Surname: ");
			scanf("%s", in_surname);
            //increase number of writes entries
            writes_entries = writes_entries + 1;
            //allocate space for new writes object
            writes_arr = (writes*) realloc(writes_arr, sizeof(writes) * (writes_entries));
            writes_arr[(writes_entries-1)].title = (char*) malloc(sizeof(char) * 150);
            //add book title to writes array
            strcpy(writes_arr[(writes_entries-1)].title,book_arr[(book_entries-1)].title);
            //works as a flag
            writes_arr[(writes_entries-1)].writer_id = 0;
            //search author array for author surname
            for(i=0; i<author_entries; i++){
                if(strcmp(author_arr[i].surname, in_surname) == 0){;
                    author_arr[i].num_of_books = author_arr[i].num_of_books + 1;
                    //if the surname is found add writer id to writes
                    writes_arr[(writes_entries-1)].writer_id = author_arr[i].writer_id;
                }
            }
            //if the surname is not found 
            if(writes_arr[(writes_entries-1)].writer_id==0){
                //increase author entries
                author_entries = author_entries + 1;
                //allocate space for new author
                author_arr = (author*) realloc(author_arr, sizeof(author) * (author_entries));
                author_arr[(author_entries-1)].surname = (char*) malloc(sizeof(char) * 150);
                author_arr[(author_entries-1)].name = (char*) malloc(sizeof(char) * 150);
			    //add author info
                printf("Name: ");
                scanf("%s", author_arr[(author_entries-1)].name);
			    strcpy(author_arr[(author_entries-1)].surname, in_surname);
                author_arr[(author_entries-1)].writer_id = author_arr[(author_entries-2)].writer_id + 1;
                author_arr[(author_entries-1)].num_of_books = 1;
                writes_arr[(writes_entries-1)].writer_id = author_arr[(author_entries-1)].writer_id;
            }
        //sort arrays
        bubble_sort_writes(writes_arr, writes_entries);
        bubble_sort_author(author_arr, author_entries);
        bubble_sort_book(book_arr, book_entries);
        //save author array to file
	    if ((author_file = fopen("author2.txt", "w")) == NULL ){
            fprintf(stderr, "File not found.\n");
                return -1;
        }
        fprintf(author_file, "%d\n", author_entries);
        for (i=0;i<author_entries; i++){
            fprintf(author_file, "%d\n", author_arr[i].writer_id);
            fprintf(author_file, "%s\n", author_arr[i].surname);
            fprintf(author_file, "%s\n", author_arr[i].name);
            fprintf(author_file, "%d\n", author_arr[i].num_of_books);
        }
        fclose(author_file);

        //save writes array to file
	    if ((writes_file = fopen("writes2.txt", "w")) == NULL ){
            fprintf(stderr, "File not found.\n");
            return -1;
        }
        fprintf(writes_file, "%d\n", writes_entries);
        for (i=0;i<writes_entries; i++){
            fprintf(writes_file, "%s\n", writes_arr[i].title);
            fprintf(writes_file, "%d\n", writes_arr[i].writer_id);
        }
        fclose(writes_file);

        //save book array to file
	    if ((book_file = fopen("book2.txt", "w")) == NULL ){
            fprintf(stderr, "File not found.\n");
            return -1;
        }
        fprintf(book_file, "%d\n", book_entries);
        for (i=0;i<book_entries; i++){
            fprintf(book_file, "%s\n", book_arr[i].title);
            fprintf(book_file, "%d\n", book_arr[i].release_date);
            fprintf(book_file, "%f\n", book_arr[i].price);
        }
        fclose(book_file);
        choice = menu();
    }else if (choice == 3) {					//author search
		printf("Surname: ");
        scanf("%s", in_surname);
        //search for author surname
        for(i=0; i<author_entries; i++){
            if(strcmp(author_arr[i].surname, in_surname) == 0){
                printf("Author Information\n");
                printf("ID: %d\n",  author_arr[i].writer_id);
                printf("Surname: %s\n",  author_arr[i].surname);
                printf("Name: %s\n",  author_arr[i].name);
                printf("Number of books: %d\n", author_arr[i].num_of_books);
                //binary search for author id in writes
                if((writes_pos=writes_search_id(writes_arr,writes_entries,author_arr[i].writer_id)) >= 0){
                    //find all the books written by this author
                    while(writes_pos<writes_entries){
                        if(writes_arr[writes_pos].writer_id == author_arr[i].writer_id){
                            if((book_pos=book_search(book_arr,book_entries,writes_arr[writes_pos].title)) >= 0){
                                if(strcmp(writes_arr[writes_pos].title,book_arr[book_pos].title)==0){
                                    printf("Books written by %s %s\n", author_arr[i].name, author_arr[i].surname);
                                    printf("Title: %s\n",  book_arr[book_pos].title);
                                    printf("Release date: %d\n",  book_arr[book_pos].release_date);
                                    printf("Price: %f\n",  book_arr[book_pos].price);
                                }
                            }
                        }
                        writes_pos++;
                    }
                }
            }
        }
               
        choice = menu();		
	}else if (choice == 4) {					//book search
		printf("Title: ");
        scanf(" %[^\n]", in_title);
        //search for book title
        if((book_pos=book_search(book_arr,book_entries,in_title)) >= 0){
            if(strcmp(in_title,book_arr[book_pos].title)==0){
                printf("Book Information\n");
                printf("Title: %s\n",  book_arr[book_pos].title);
                printf("Release Date: %d\n",  book_arr[book_pos].release_date);
                printf("Price: %f\n",  book_arr[book_pos].price);
                for(i = 0; i < writes_entries; i++){
                    if(strcmp(writes_arr[i].title, book_arr[book_pos].title) == 0){
                        if((author_pos=author_search(author_arr,author_entries,writes_arr[i].writer_id)) >= 0){
                            printf("Book author information\n");
                            printf("ID: %d\n",  author_arr[author_pos].writer_id);
                            printf("Surname: %s\n",  author_arr[author_pos].surname);
                            printf("Name: %s\n",  author_arr[author_pos].name);
                            printf("Number of books: %d\n",  author_arr[author_pos].num_of_books);
                        }
                    }         
                }
            }    
                
        }        
        choice=menu();		
    }else if (choice == 5){ //Delete author
        printf("ID: ");
        scanf("%d", &in_id);
        //search for author
        if((author_pos=author_search(author_arr,author_entries,in_id)) >= 0){
            if((writes_pos=writes_search_id(writes_arr,writes_entries,author_arr[author_pos].writer_id)) >= 0){
                //to delete all writes and book entries related to author
                while(writes_pos<writes_entries){
                    if(writes_arr[writes_pos].writer_id == author_arr[author_pos].writer_id){
                        if((book_pos=book_search(book_arr,book_entries,writes_arr[writes_pos].title)) >= 0){
                            if(strcmp(writes_arr[writes_pos].title,book_arr[book_pos].title)==0){
                                //delete books
                                swap_book(&book_arr[book_pos], &book_arr[book_entries-1]);
                                book_entries--; 
                            }
                        }
                        //delete writes
                        swap_writes(&writes_arr[writes_pos], &writes_arr[writes_entries-1]);
                        writes_entries--; 
                    }
                    writes_pos++;
                }
            }
            //delete author
            swap_author(&author_arr[author_pos], &author_arr[author_entries-1]);
            author_entries--;
        }
        //sort arrays
        bubble_sort_writes(writes_arr, writes_entries);
        bubble_sort_author(author_arr, author_entries);
        bubble_sort_book(book_arr, book_entries);
        //save author array to file
	    if ((author_file = fopen("author2.txt", "w")) == NULL ){
            fprintf(stderr, "File not found.\n");
                return -1;
        }
        fprintf(author_file, "%d\n", author_entries);
        for (i=0;i<author_entries; i++){
            fprintf(author_file, "%d\n", author_arr[i].writer_id);
            fprintf(author_file, "%s\n", author_arr[i].surname);
            fprintf(author_file, "%s\n", author_arr[i].name);
            fprintf(author_file, "%d\n", author_arr[i].num_of_books);

        }
        fclose(author_file);

        //save writes array to file
	    if ((writes_file = fopen("writes2.txt", "w")) == NULL ){
            fprintf(stderr, "File not found.\n");
            return -1;
        }
        fprintf(writes_file, "%d\n", writes_entries);
        for (i=0;i<writes_entries; i++){
            fprintf(writes_file, "%s\n", writes_arr[i].title);
            fprintf(writes_file, "%d\n", writes_arr[i].writer_id);
        }
        fclose(writes_file);

        //save book array to file
	    if ((book_file = fopen("book2.txt", "w")) == NULL ){
            fprintf(stderr, "File not found.\n");
            return -1;
        }
        fprintf(book_file, "%d\n", book_entries);
        for (i=0;i<book_entries; i++){
            fprintf(book_file, "%s\n", book_arr[i].title);
            fprintf(book_file, "%d\n", book_arr[i].release_date);
            fprintf(book_file, "%f\n", book_arr[i].price);

        }
        fclose(book_file);
        choice = menu();
    }else if (choice == 6){ //delete book
        printf("Title: ");
        scanf(" %[^\n]", in_title);
        //search book
        if((book_pos=book_search(book_arr,book_entries,in_title)) >= 0){
            for(i=0; i < writes_entries; i++){
                if(strcmp(writes_arr[i].title, book_arr[book_pos].title) == 0){
                    if((author_pos=author_search(author_arr,author_entries,writes_arr[i].writer_id)) >= 0){
                        //decrease the number of books for author
                        author_arr[author_pos].num_of_books = author_arr[author_pos].num_of_books - 1;
                    }
                    //delete writes
                    swap_writes(&writes_arr[i], &writes_arr[writes_entries-1]);
                    writes_entries--;
                }
            }
            //delete book
            swap_book(&book_arr[book_pos], &book_arr[book_entries-1]);
            book_entries--;
        }
        //bubble sort arrays
        bubble_sort_writes(writes_arr, writes_entries);
        bubble_sort_author(author_arr, author_entries);
        bubble_sort_book(book_arr, book_entries);
        //save author array to file
	    if ((author_file = fopen("author2.txt", "w")) == NULL ){
            fprintf(stderr, "File not found.\n");
                return -1;
        }
        fprintf(author_file, "%d\n", author_entries);
        for (i=0;i<author_entries; i++){
            fprintf(author_file, "%d\n", author_arr[i].writer_id);
            fprintf(author_file, "%s\n", author_arr[i].surname);
            fprintf(author_file, "%s\n", author_arr[i].name);
            fprintf(author_file, "%d\n", author_arr[i].num_of_books);

        }
        fclose(author_file);

        //save writes array to file
	    if ((writes_file = fopen("writes2.txt", "w")) == NULL ){
            fprintf(stderr, "File not found.\n");
            return -1;
        }
        fprintf(writes_file, "%d\n", writes_entries);
        for (i=0;i<writes_entries; i++){
            fprintf(writes_file, "%s\n", writes_arr[i].title);
            fprintf(writes_file, "%d\n", writes_arr[i].writer_id);
        }
        fclose(writes_file);

        //save book array to file
	    if ((book_file = fopen("book2.txt", "w")) == NULL ){
            fprintf(stderr, "File not found.\n");
            return -1;
        }
        fprintf(book_file, "%d\n", book_entries);
        for (i=0;i<book_entries; i++){
            fprintf(book_file, "%s\n", book_arr[i].title);
            fprintf(book_file, "%d\n", book_arr[i].release_date);
            fprintf(book_file, "%f\n", book_arr[i].price);
        }
        fclose(book_file);
        choice = menu();
    }else{
        printf("Invalid number\n");
        choice = menu();
    }
        
    }
    //free book array
    for(i=0;i<book_entries;i++){
       free(book_arr[i].title);
    }
    free(book_arr);
    //free author array
    for(i=0;i<author_entries;i++){
       free(author_arr[i].surname);
       free(author_arr[i].name);
    }
    free(author_arr);
    //free writes array
    for(i=0;i<writes_entries;i++){
       free(writes_arr[i].title);
    }
    free(writes_arr);
    return 0;
}

int menu()
{
    int choice;

    printf("Input:\n");
    printf("1.Insert new writer record\n");
    printf("2.Insert new book record\n");
    printf("3.Search a writer record\n");
    printf("4.Search a book record\n");
    printf("5.Delete a writer record\n");
    printf("6.Delete a book record\n");
    printf("7.Exit\n");

    scanf("%d", &choice);

    return choice;
}

void bubble_sort_book(book *book_arr, int book_entries)
{
    int i,j;
    for(i=0;i<book_entries-1;i++){
        for (j=0;j<book_entries-i-1;j++){
            if(strcmp(book_arr[j].title, book_arr[j+1].title)>0){
                swap_book(&book_arr[j], &book_arr[j+1]);
            }
        }
    }
}

void bubble_sort_author(author *author_arr, int author_entries)
{
    int i,j;
    for(i=0;i<author_entries-1;i++){
        for (j=0;j<author_entries-i-1;j++){
            if(author_arr[j].writer_id > author_arr[j+1].writer_id){
                swap_author(&author_arr[j], &author_arr[j+1]);
            }
        }
    }
}

void bubble_sort_writes(writes *writes_arr, int writes_entries)
{
    int i,j;
    for(i=0;i<writes_entries-1;i++){
        for (j=0;j<writes_entries-i-1;j++){
            if(writes_arr[j].writer_id>writes_arr[j+1].writer_id){
                swap_writes(&writes_arr[j], &writes_arr[j+1]);
            }else if(writes_arr[j].writer_id==writes_arr[j+1].writer_id){
			    if(strcmp(writes_arr[j].title, writes_arr[j+1].title)>0){
                    swap_writes(&writes_arr[j], &writes_arr[j+1]);  
                }
            }
        }
    }
}
void swap_book(book *b1, book *b2)
{
    book tmp;

    tmp = *b1;
    *b1 = *b2;
    *b2 = tmp;
}
void swap_author(author *author1, author *author2)
{
    author tmp;

    tmp = *author1;
    *author1 = *author2;
    *author2 = tmp;
}
void swap_writes(writes *writes1, writes *writes2)
{
	writes tmp;

    tmp = *writes1;
    *writes1 = *writes2;
    *writes2 = tmp;	
}

int author_search(author* author_arr, int author_entries, int in_id)
{
    int lb, mid, ub, pos = 0;
    //init bounds
    lb = 0;                            
    ub = author_entries;                            
    do
    {
        //compare id with the middle of array
        mid = (int)(lb + ub) / 2;      
        if(in_id < author_arr[mid].writer_id)     
            ub = mid - 1;                       
        else if(in_id > author_arr[mid].writer_id)
            lb = mid + 1;        
    //repeat the process till lb doesn't becomes ub and string is found   
    }while((in_id != author_arr[mid].writer_id) && lb <= ub);
    //if id is found
    if(in_id == author_arr[mid].writer_id){
        pos=mid;
        return pos;
    //if id is not found
    }else if(in_id != author_arr[mid].writer_id) {                                        //if not found
        printf("Author not found \n");
        return -1;
    }
}

int book_search(book* book_arr, int book_entries, char* in_title)
{
    int lb, mid, ub, pos = 0;
    //init bounds
    lb = 0;                             
    ub = book_entries;                            
    do
    {
        //compare title with the middle of the array
        mid = (int)(lb + ub) / 2;             
        if((strcmp(in_title, book_arr[mid].title))<0)      
            ub = mid - 1;                          
        else if((strcmp(in_title, book_arr[mid].title))>0)
            lb = mid + 1;                      
    }while((strcmp(in_title, book_arr[mid].title)!=0) && lb <= ub);
    //if title is found
    if((strcmp(in_title, book_arr[mid].title))==0){
        pos=mid;
        return pos;
        
    //if title is not found
    }else{                                        
        printf("Book not found \n");
        return -1;
    }
}

int writes_search_id(writes* writes_arr, int writes_entries, int in_writer_id)
{
    int lb, mid, ub, pos=0;
    lb = 0;
    ub = writes_entries; 
    do
    {
        //compare id with the middle of the array 
        mid = (int)(lb + ub) / 2;
        if(in_writer_id < writes_arr[mid].writer_id)
            ub = mid - 1;
        else if(in_writer_id > writes_arr[mid].writer_id)
            lb = mid + 1;
    }while((in_writer_id != writes_arr[mid].writer_id) && lb <= ub);
    //if id is found
    if(in_writer_id == writes_arr[mid].writer_id){
            pos=mid;
            return pos;
    //if id is not found
    }else{
        printf("Write not found \n");
        return -1;
    }
}